### PR TITLE
Roger dev

### PR DESCRIPTION
**Pull request by rogxue**
Do you think I'm pretty🎶🎵🎶🎵

### CODE REVIEW

**Comment by ryanpitt** [comment]
Crashes when started with no database.

```
Track block not found. (green 63)
Exception in thread "main" java.lang.NullPointerException
	at track_model.TrackModel.getPositionAlongBlock(TrackModel.java:825)
	at track_model.TrackModel.<init>(TrackModel.java:59)
	at integration.Main.initializeModules(Main.java:65)
	at integration.Main.main(Main.java:50)
```

**Comment by rogxue** [comment]
Forgot to remove a line I used for testing

**Comment by ryanpitt** [comment]
Can't launch visual track model map.

**Comment by rogxue** [comment]
I wiped everything and couldn't reproduce that

**Comment by rogxue** [comment]
Is there an images folder inside the track_model folder? Do the images appear in Netbeans in the packages?

packages

**Comment by ryanpitt** [comment]
Yup, I see all those images. Still crashes.

**Comment by ryanpitt** [comment]
Hmm, a fresh clone didn't crash. Weird.

**Comment by rogxue** [comment]
I've researched this all afternoon and honestly have no idea why it wouldn't work.

**Comment by rogxue** [comment]
In whatever directory you're building the project, does the /build/classes/track_model/images folder exist and are the images in there?

**Comment by ryanpitt** [comment]
If I add my source directory (which is different than my build directory) to my classpath it works!

Why is that? Is that how it should work?

**Pull request merged**
